#!/usr/bin/env bash

pushd "$(dirname "$0")" > /dev/null
popd > /dev/null

STATUS_CONNECTED="connected"
STATUS_DISCONNECTED="disconnected"

function show_status()
{
  INFO_STRING=$(bluetoothctl -- info $HEADSET_ID)
  STATUS=$(echo "$INFO_STRING" | grep "Connected" | cut -d ":" -f 2 | tr -d '[:space:]')
  [[ "$STATUS" == "yes" ]] && echo $STATUS_CONNECTED && exit 0
  [[ "$STATUS" == "no" ]] && echo $STATUS_DISCONNECTED && exit 0
  echo "Unknown status $STATUS" && exit 1
}

STATUS=$(show_status)

case $BLOCK_BUTTON in
  1) notify-send "BT headset module" "\- Right-click to display device info.
- Middle-click to connect/disconnect." ;;
  2)
    if [[ "$STATUS_CONNECTED" == "$STATUS" ]]
    then
      bluetoothctl -- disconnect $HEADSET_ID > /dev/null
    else
      bluetoothctl -- connect "$HEADSET_ID" > /dev/null
    fi
    ;;
  3) notify-send "Headset info" "$(bluetoothctl -- info $HEADSET_ID | head -n 10)" ;;
esac

echo " $(bluetoothctl -- info $HEADSET_ID | grep "Name" | cut -d ":" -f 2 | tr -d '[:space:]')" # full text
echo "" # short text

[[ "$STATUS_CONNECTED" == "$STATUS" ]] && echo "#00FF00"
